# Group 1, MLOps (DDM501.22), FSB
# Nguyen Sy Hung (25MSA33055)
"""Shared agent output schemas."""

from dataclasses import dataclass
from typing import Any


@dataclass
class AgentOutput:
    """Output generated by an agent.

    ``response`` is shown to the user. ``prompt`` records the rendered prompt
    used for the selected response backend.
    """

    response: str
    prompt: str
    generation_mode: str = "template"
    model: str = "none"
    usage_details: dict[str, int] | None = None
    provider_usage: dict[str, Any] | None = None
